[workspace]

resolver = "1"

members = [
    "combinations",
    "conway",
    "min-queue",
    "lru-cache",
    "mpsc",
    "prefix",
    "comm",
    "flatmap",
    "trust",
    "examples",
    "itertools",
]
